// <auto-generated />
using System;
using ACCAI.Infrastructure.DataSource;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ACCAI.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251023201704_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ACCAI.Domain.Entities.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Cuenta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EstadoContrato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FecEfectiva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FecInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FecSaldo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FecTerminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FecUltimoAporte")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdAgte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NroDocum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroContrato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PclidAfi")
                        .HasColumnType("int");

                    b.Property<string>("PlanProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Producto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SaldoCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SaldoRendimientos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SaldoUn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoDocum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ValorAporteMes")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Contrato", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cuenta = 10001m,
                            EstadoContrato = "Activo",
                            FecEfectiva = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FecInicio = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FecSaldo = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FecTerminacion = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FecUltimoAporte = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdAgte = "5834",
                            NroDocum = "123456789",
                            NumeroContrato = "10001",
                            PclidAfi = 101,
                            PlanProducto = "Plan Básico",
                            Producto = "Ahorro Programado",
                            Saldo = 1500000m,
                            SaldoCapital = 1200000m,
                            SaldoRendimientos = 300000m,
                            SaldoUn = 1500000m,
                            TipoDocum = "CC",
                            ValorAporteMes = 50000m
                        },
                        new
                        {
                            Id = 2,
                            Cuenta = 10002m,
                            EstadoContrato = "Activo",
                            FecEfectiva = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FecInicio = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FecSaldo = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FecTerminacion = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FecUltimoAporte = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdAgte = "5834",
                            NroDocum = "987654321",
                            NumeroContrato = "10002",
                            PclidAfi = 102,
                            PlanProducto = "Premium",
                            Producto = "Fondo de Inversión",
                            Saldo = 3500000m,
                            SaldoCapital = 3000000m,
                            SaldoRendimientos = 500000m,
                            SaldoUn = 3500000m,
                            TipoDocum = "CC",
                            ValorAporteMes = 200000m
                        });
                });

            modelBuilder.Entity("ACCAI.Domain.Entities.Voter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Nid")
                        .IsUnique();

                    b.ToTable("Voters", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
